### Register
POST http://127.0.0.1:5000/api/user/register
Content-Type: application/json

{"email" :"q@q.q213","password": "123" }

### Login

POST http://127.0.0.1:5000/api/user/login
Content-Type: application/json

{"email" :"q@q.q1","password": "123" }

### Cast Vote

POST http://127.0.0.1:5000/api/vote
Authorization: token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YTc0MDg2NjY3ZTBhOWFjM2M1NjFhMiIsImlhdCI6MTczOTA0MzA5MywiZXhwIjoxNzM5MDQ2NjkzfQ.uSMtP5Xrq6WeHkBMKjB4AFYRcE5_UscGON71cVoDRwQ
Content-Type: application/json

{"option" :"Dog" }

### Get Votes for all
GET http://127.0.0.1:5000/api/votes 